### ISSUE TITLE
Make editor movement speed an inspector variable

### ISSUE THREAD

**Issue by Adrian-Wennberg** [bouvet/BouvetDevelopmentKit#21]
Currently editor movement speed is locked to a decent value for human sized objects value (something like 1cm per second). It would be nice to have this as an editable value in the inspector.  Potentially a slider.

**Comment by Adrian-Wennberg** [comment]
Just noticed that movement speed is also tied to the FPS which is just horrible. So this in now a bug as well.

**Comment by OlePLarsen** [comment]
Both fixed in commit 2bb8998b672344afee11ac6798aa6f39ba3c3d0e .
