### ISSUE TITLE
Hand-state management bug when closing and reopening app. Can use 1 hand at a time, not not both.

### ISSUE THREAD

**Issue by OlePLarsen** [bouvet/BouvetDevelopmentKit#25]
During testing today a bug popped up that was fairly odd.
The application worked fine, handed it off to a colleague to test, and he ran the 'adjust your eyes', which then minimized the app.

When returning to the app after adjusting his eyes, it was no longer possible to use both hands at once in the app.
You could use the right hand, or left hand, but if you had both hands visible, they would be disabled.
I assume it might have been something toggling states that didn't update correctly due to the app losing focus. 

Log can be provided on request.
I imagine the root cause is that we don't really have much handling for managing the app losing focus / getting minimized.

**Comment by MartinHelvig** [comment]
@OlePLarsen is it possible to still get that Log?

**Comment by OlePLarsen** [comment]
Probably not, I imagine it's been overwritten or wiped since then. Can't remember when I logged this issue.
________________________________

**Comment by MartinHelvig** [comment]
Understandable, next time just post the Log, better with to much than to little.
