### ISSUE TITLE
Breaking changes from v1.0.2 to v1.0.3

### ISSUE THREAD

**Issue by Adrian-Wennberg** [bouvet/BouvetDevelopmentKit#28]
In version v1.0.3, we moved a lot of code from the package into samples. This has caused some breaking changes and a lot of pain when updating from v1.0.2 or earlier. To work around this and future issues regarding this, we will move the samples back into the package and not rely on samples too much in the future. 

This will be an extensive upgrade and take a bit of time, but by the end of it, we will have release v1.1.0 which will be cleaner and easier to import, and we will update the documentation accordingly.

**Comment by Adrian-Wennberg** [comment]
For those wondering how the breaking changes manifested, we do not have a detailed writeup, but the crux of the issue is that updating the package has been causing objects in our scene to lose connections to BDK scripts. Also, when updating the package, the samples do not update, and when updating the samples, you can esially get GUID collisions between old and new samples, and again sometimes loose links form the scene or from prefabs to your scripts. 

This sort of issues makes updating the package a lot more difficult since the scene and prefabs in your project that use affected BDK scripts will need to be manually fixed, which in larger projects gets overwhelming quickly.

**Comment by MartinHelvig** [comment]
Fixed in 1.1.0
