### ISSUE TITLE
Feature request: event for being held

### ISSUE THREAD

**Issue by brunerune** [bouvet/BouvetDevelopmentKit#30]
Would love to have an event on Grabbable which tells me if an item is being held. Now I have to constantly check the boolean value for every frame to decide if the item has been picked up or dropped. Thank you

**Comment by Adrian-Wennberg** [comment]
Grabbable has a [`beingHeld`](https://github.com/bouvet/BouvetDevelopmentKit/blob/6b6e2f092d739de6fe200447c29e216d99b26962/Scripts/Runtime/Foundations/Functionallity/Hands/Grabbable.cs#L19) property that you can check, although I am not sure if this is available in your current version 😕

**Comment by brunerune** [comment]
Yes, but that is a boolean value, which means that I need to check its value for each frame. I would prefer to have an event that I can listen to, which fires if an item is being picked up or dropped.

**Comment by Adrian-Wennberg** [comment]
In that case you can use the [inputManager.OnManipulationEnded](https://github.com/bouvet/BouvetDevelopmentKit/blob/6b6e2f092d739de6fe200447c29e216d99b26962/Scripts/Runtime/Foundations/Functionallity/Hands/Grabbable.cs#L45). You can se an example of an event being called with it [here](https://github.com/bouvet/BouvetDevelopmentKit/blob/6b6e2f092d739de6fe200447c29e216d99b26962/Scripts/Runtime/Foundations/Functionallity/Hands/Grabbable.cs#L126).

In any case, it is pretty common and not very expensive to check every frame, so both options work fine.

**Comment by Adrian-Wennberg** [comment]
This was resolved using the events from the last comment
