### ISSUE TITLE
Grabbing grabbables still possible when TwoHandGrabbables script is disabled.

### ISSUE THREAD

**Issue by bardsodal** [bouvet/BouvetDevelopmentKit#32]
When deactivating the TwoHandGrabbable script the object can still be interacted with as it is still subscribed to the interaction events (as long as it still has a collider that can be targeted). There should be a check in BeginInteraction that checks if the script is enabled, and returns if it is not. Deactivating the script should be a clear indication that the user does not want the object to be interacted with.

This should be fixed for both Grabbable and TwoHandGrabbable.

https://github.com/bouvet/BouvetDevelopmentKit/blob/6b6e2f092d739de6fe200447c29e216d99b26962/Scripts/Runtime/Foundations/Functionallity/Hands/Grabbable.cs#L66

https://github.com/bouvet/BouvetDevelopmentKit/blob/6b6e2f092d739de6fe200447c29e216d99b26962/Scripts/Runtime/Foundations/Functionallity/Hands/TwoHandGrabbable.cs#L50

**Comment by Adrian-Wennberg** [comment]
I think in general we should move a lot of our event handling to onEnable and onDisable instead of start and OnDestroy. In my opinion, this would make interactions like this much more resillient and it would behave more as expected.

**Comment by bardsodal** [comment]
Just be aware that starting event handling onEnable might break the interaction as InputManager might not have completed it setup yet. 

https://docs.unity3d.com/Manual/ExecutionOrder.html

**Comment by Adrian-Wennberg** [comment]
Thank you for the heads up, although I still feel that's the right way to go 😉 

We can have a go at changing it, and potentially not do the initial subscribe in staer, andhave it unsubscribe and resubscribe with onEnable and OnDisable after that.

**Comment by MartinHelvig** [comment]
Fixed in version 1.1.1.
