### ISSUE TITLE
Issue when deleting colliders placed in global origin

### ISSUE THREAD

**Issue by brunerune** [bouvet/BouvetDevelopmentKit#33]
When deleting colliders placed in global origin (0,0,0), multiple errors occur every second with Unity complaining about a missing reference. It is believed to be because (0,0,0) is within the index tip of the hand indicator. 
![image](https://user-images.githubusercontent.com/97032407/160591613-f47e35a0-470b-4da5-b007-18782cfe8b5d.png)

**Comment by MartinHelvig** [comment]
Fixed in version 1.1.1.
