### ISSUE TITLE
Logs are not written to log file on HoloLens

### ISSUE THREAD

**Issue by Adrian-Wennberg** [bouvet/BouvetDevelopmentKit#42]
BDKLogger currenly writes to the unity debug log in the editor but not on HoloLens. Instead it runs Console.WriteLine which does not seem to log anywhere. Spesifically, the log file created on the device does not contain logs form the BDK logger as it stands. 

Should we change it to use Debug.Log instead? This has been tested and seems to work as expected on HoloLens.

**Comment by MartinHelvig** [comment]
Fixed in version 1.1.1.
